---
# Source: cert-manager-webhook-civo/templates/apiservice.yaml
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.civo.webhook.okteto.com
  labels:
    helm.sh/chart: cert-manager-webhook-civo-0.2.0
    app.kubernetes.io/name: cert-manager-webhook-civo
    app.kubernetes.io/instance: cert-manager-webhook-civo
    app.kubernetes.io/version: "0.2.0"
    app.kubernetes.io/managed-by: Helm
  annotations:  
     cert-manager.io/inject-ca-from: "cert-manager/cert-manager-webhook-civo-webhook-tls"
spec:
  group: civo.webhook.okteto.com
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: cert-manager-webhook-civo
    namespace: cert-manager
  version: v1alpha1
